async function main() {
  return
}

main()
  .catch((error) => console.error(error))
  .then(() => process.exit(0))
